#rowCount = 0
#
#sendFileToServer = (formData, status) ->
#  uploadURL = '/articles/upload_image'
#  #Upload URL
#  extraData = {}
#  #Extra Data.
#  jqXHR = $.ajax(
#    xhr: ->
#      xhrobj = $.ajaxSettings.xhr()
#      if xhrobj.upload
#        xhrobj.upload.addEventListener 'progress', ((event) ->
#          percent = 0
#          position = event.loaded or event.position
#          total = event.total
#          if event.lengthComputable
#            percent = Math.ceil(position / total * 100)
#          #Set progress
#          status.setProgress percent
#          return
#        ), false
#      xhrobj
#    url: uploadURL
#    type: 'POST'
#    contentType: false
#    processData: false
#    cache: false
#    data: formData
#    success: (data) ->
#      status.setProgress 100
#      $('#status1').append 'File upload Done<br>'
#      return
#  )
#  status.setAbort jqXHR
#  return
#
#createStatusbar = (obj) ->
#  rowCount++
#  row = 'odd'
#  if rowCount % 2 == 0
#    row = 'even'
#  @statusbar = $('<div class=\'statusbar ' + row + '\'></div>')
#  @filename = $('<div class=\'filename\'></div>').appendTo(@statusbar)
#  @size = $('<div class=\'filesize\'></div>').appendTo(@statusbar)
#  @progressBar = $('<div class=\'progressBar\'><div></div></div>').appendTo(@statusbar)
#  @abort = $('<div class=\'abort\'>Abort</div>').appendTo(@statusbar)
#  obj.after @statusbar
#
#  @setFileNameSize = (name, size) ->
#    sizeStr = ''
#    sizeKB = size / 1024
#    if parseInt(sizeKB) > 1024
#      sizeMB = sizeKB / 1024
#      sizeStr = sizeMB.toFixed(2) + ' MB'
#    else
#      sizeStr = sizeKB.toFixed(2) + ' KB'
#    @filename.html name
#    @size.html sizeStr
#    return
#
#  @setProgress = (progress) ->
#    progressBarWidth = progress * @progressBar.width() / 100
#    @progressBar.find('div').animate({ width: progressBarWidth }, 10).html progress + '% '
#    if parseInt(progress) >= 100
#      @abort.hide()
#    return
#
#  @setAbort = (jqxhr) ->
#    sb = @statusbar
#    @abort.click ->
#      jqxhr.abort()
#      sb.hide()
#      return
#    return
#
#  return
#
#handleFileUpload = (files, obj) ->
#  i = 0
#  while i < files.length
#    fd = new FormData
#    fd.append 'file', files[i]
#    status = new createStatusbar(obj)
#    #Using this we can set progress.
#    status.setFileNameSize files[i].name, files[i].size
#    sendFileToServer fd, status
#    i++
#  return
#
#$(document).ready ->
#  obj = $('#dragandrophandler')
#  obj.on 'dragenter', (e) ->
#    e.stopPropagation()
#    e.preventDefault()
#    $(this).css 'border', '2px solid #0B85A1'
#    return
#  obj.on 'dragover', (e) ->
#    e.stopPropagation()
#    e.preventDefault()
#    return
#  obj.on 'drop', (e) ->
#    $(this).css 'border', '2px dotted #0B85A1'
#    e.preventDefault()
#    files = e.originalEvent.dataTransfer.files
#    #We need to send dropped files to Server
#    handleFileUpload files, obj
#    return
#  $(document).on 'dragenter', (e) ->
#    e.stopPropagation()
#    e.preventDefault()
#    return
#  $(document).on 'dragover', (e) ->
#    e.stopPropagation()
#    e.preventDefault()
#    obj.css 'border', '2px dotted #0B85A1'
#    return
#  $(document).on 'drop', (e) ->
#    e.stopPropagation()
#    e.preventDefault()
#    return
#  return
#
## ---
## generated by js2coffee 2.0.0